Repository UniAuth/uniauth-backend, pull requests merged in 2021-03, with the labels that each got.

#151 chore(ci): remove lables workflow
  .github/workflows/labels.yml
Labels: gssoc21, level1, merged

#174 feat(ui): add card for user profile
  views/dashboard/profile.hbs
Labels: frontend, gssoc21, level3

#177 feat(ui): add navbar logo to edit profile page
  views/profile/edit.hbs
Labels: gssoc21, level2

#179 fix(app): fixed minimum description condition
  src/application/dto/create-application.dto.ts
Labels: gssoc21, level2
