Repository UniAuth/uniauth-backend, pull requests merged in 2021-02, with the labels that each got.

#35 deployed docs on Github pages
  .github/workflows/doc.yml
  README.md
  package.json
Labels: user=kdsinghcoder:score=25

#36 add password validation
  views/account/login.hbs
  views/account/register.hbs
Labels: user=kdsinghcoder:score=25

#47 docs(readme): update screenshots
  README.md
Labels: easy / 25 points, user=kdsinghcoder:score=25

#53 E-mail module implemented. This fixes issue #43
  config/default.yml
  src/mailer/constants/confirmEmailToken.constants.ts
  src/mailer/mailer.controller.spec.ts
  src/mailer/mailer.controller.ts
  src/mailer/mailer.module.ts
  src/mailer/mailer.service.spec.ts
  src/mailer/mailer.service.ts
Labels: user=MASTERCHIEF011:score=50

#50 Add feature to update user profile
  src/dashboard/dashboard.controller.ts
  src/dashboard/dashboard.module.ts
  src/dashboard/dashboard.service.ts
  src/user/dto/update-user.dto.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  views/dashboard/data.hbs
  views/dashboard/profile.hbs
  views/profile/edit.hbs
Labels: user=tanay13:score=25, user=tanay13:score=50

#73 docs(readme): remove travic-ci badge
  README.md
Labels: user=kdsinghcoder:score=10

#80 fix(ui): hide passwd input field in passwd reset
  views/password/reset.hbs
Labels: user=MASTERCHIEF011:score=25

#79 feat(passwd reset): compare passwd before reset
  views/password/reset.hbs
Labels: user=MASTERCHIEF011:score=25

#82 fix(passwd reset): share email via form data
  views/password/request.hbs
Labels: user=MASTERCHIEF011:score=10

#84 test(dashboard): controller setup
  src/dashboard/dashboard.controller.spec.ts
Labels: user=tanay13:score=25

#88 test(dashboard): add test for service
  src/dashboard/dashboard.service.spec.ts
Labels: user=tanay13:score=25

#85 feat(mailer): add tests for service
  src/mailer/mailer.service.spec.ts
Labels: user=MASTERCHIEF011:score=25

#90 test(application): add test for service
  src/application/application.service.spec.ts
Labels: user=MASTERCHIEF011:score=25

#89 feat(account): add test for controller
  src/account/account.controller.spec.ts
Labels: user=MASTERCHIEF011:score=25

#92 test(auth): add tests for service
  src/auth/auth.service.spec.ts
Labels: user=MASTERCHIEF011:score=25

#93 test(application): add tests for controller
  src/application/application.controller.spec.ts
Labels: user=MASTERCHIEF011:score=25

#95 docs(readme): add steps to get sendgrid API
  README.md
Labels: user=MASTERCHIEF011:score=25

#98 test(user): fix service test failing
  src/user/user.service.spec.ts
Labels: user=tanay13:score=50

#101 fix(app): server crash on load
  src/main.ts
Labels: user=MASTERCHIEF011:score=50

#103 fix(passwd reset): add length check
  views/password/reset.hbs
Labels: user=MASTERCHIEF011:score=25

#99 feat(application): add delete feature
  src/application/application.service.ts
  src/dashboard/dashboard.controller.ts
  views/dashboard/dev.hbs
Labels: user=MASTERCHIEF011:score=50

#74 chore(build): add dockerfile
  Dockerfile
Labels: user=kdsinghcoder:score=25

#105 fix(passwd): update regex
  views/account/register.hbs
  views/password/reset.hbs
Labels: user=kdsinghcoder:score=25

#116 fix(ui): cards combining into single card
  views/dashboard/dev.hbs
Labels: user=kdsinghcoder:score=25

#118 chore(git): setup pre commit hook for lint and format
  package.json
Labels: user=MASTERCHIEF011:score=25

#109 feat(user): show logged in user list
  src/application/application.schema.ts
  src/application/application.service.ts
  src/dashboard/dashboard.controller.ts
  src/user/user.schema.ts
  src/user/user.service.ts
  views/dashboard/data.hbs
  views/dashboard/details.hbs
  views/dashboard/dev.hbs
Labels: user=tanay13:score=100

#121 refactor(views): add partials to avoid code duplication
  src/main.ts
  views/dashboard/dashboard.hbs
  views/dashboard/data.hbs
  views/dashboard/details.hbs
  views/dashboard/dev.hbs
  views/dashboard/profile.hbs
  views/partials/header.hbs
Labels: user=kdsinghcoder:score=100

#114 docs(readme): add status badges
  README.md
Labels: user=kdsinghcoder:score=25

#125 fix(application): error alert on creation
  views/dashboard/dev.hbs
Labels: user=MASTERCHIEF011:score=50

#126 chore(user): migrate route to application controller
  src/dashboard/dashboard.controller.ts
  src/user/user.controller.ts
  views/dashboard/profile.hbs
  views/profile/edit.hbs
Labels: user=kdsinghcoder:score=25

#132 chore(ci): run test on pull request
  .github/workflows/ci.yml
Labels: user=MASTERCHIEF011:score=25

#128 docs(ci): add deploy to heroku button
  README.md
  app.json
Labels: user=kdsinghcoder:score=50

#131 fix(passwd): re-routing pages
  src/account/account.controller.ts
  views/partials/server-response.hbs
Labels: medium / 50 points, user=MASTERCHIEF011:score=50

#133 chore(ci): integrated codecov coverage
  .github/workflows/workflow.yml
  test/jest-e2e.json
Labels: user=MASTERCHIEF011:score=50

#134 fixX(application): fix application count
  src/application/application.service.ts
  src/dashboard/dashboard.controller.ts
Labels: user=tanay13:score=50

#144 fix(ui): onclick copy to clipboard function
  views/dashboard/dev.hbs
Labels: user=MASTERCHIEF011:score=25

#142 feat(ui): add confirmation before delete feature
  views/dashboard/dev.hbs
Labels: medium / 50 points, user=MASTERCHIEF011:score=50

#137 feat(ui): add box shadow to app cards
  views/dashboard/dev.hbs
Labels: user=MASTERCHIEF011:score=25

#141 chore(app): remove unused functions
  src/user/user.controller.ts
Labels: user=kdsinghcoder:score=25

#135 feat(app): customize from single file
  config/appData.ts
  config/default.yml
  src/account/account.controller.ts
  src/app.controller.ts
  src/dashboard/dashboard.controller.ts
  views/account/login.hbs
  views/account/register.hbs
  views/landing.hbs
  views/partials/header.hbs
  views/partials/server-response.hbs
  views/password/request.hbs
  views/password/reset.hbs
  views/profile/edit.hbs
Labels: user=kdsinghcoder:score=50

#140 Fixed all linting issues
  src/account/account.controller.ts
  src/account/account.service.spec.ts
  src/app.module.ts
  src/application/application.controller.ts
  src/application/application.schema.ts
  src/application/application.service.spec.ts
  src/application/application.service.ts
  src/application/dto/create-application.dto.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auxiliary/exceptions/mongo.exceptions.ts
  src/config/mongoose.config.ts
  src/dashboard/dashboard.controller.ts
  src/dashboard/dashboard.service.ts
  src/mailer/mailer.module.ts
  src/mailer/mailer.service.spec.ts
  src/mailer/mailer.service.ts
  src/main.ts
  src/user/user.repository.ts
  src/user/user.schema.ts
  src/user/user.service.spec.ts
  src/user/user.service.ts
Labels: user=kdsinghcoder:score=100

#75 compose file added
  docker-compose.yml
Labels: user=kdsinghcoder:score=25
